name: MobRain
main: me.NerdsWBNerds.MobRain.MobRain
version: 2.2.1
commands:
    drops:
      description: Remove mob drop in certain radius.
      usage: /drops <radius>
    mrain:
      description: Create a creature storm.
      usage: /<command> <amount> <mob> (radius) (player)
      aliases: [mr]
    killmobs:
      description: Kill mobs in specific radius.
      usage: /<command> <radius>
      aliases: [mrbutcher] [butcher]